#database
MONGO_URL = "mongodb://localhost:27017/"
MONGO_DB_NAME = "EsfiQuizBot"

#redis
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

#bot
BOT_TOKEN = "8157447181:AAFpGVEQzwd3OPVawDNM4EoOQKS9BHBy3NI"
BOT_USER_ID = 8157447181
BOT_USERNAME = "EsfiQuizBot"
BOT_NAME = "EsfiQuizBot"


#sponsor
SPONSOR_CHANNEL_ID = -1002425240348
SPONSOR_CHANNEL_NAME = "Esfima | تکنولوژی"
SPONSOR_CHANNEL_URL = "https://t.me/Esfima"



#admin
ADMIN_ID = 7903509636

# تغییر ADMIN_ID به ADMIN_IDS به صورت لیست
ADMIN_IDS = ["7903509636"]

#Topic Settings
TOPIC_NAME_MAX_LENGTH = 20
TOPIC_NAME_MIN_LENGTH = 3
TOPIC_DESCRIPTION_MAX_LENGTH = 200
TOPIC_DESCRIPTION_MIN_LENGTH = 20

#Question Settings
QUESTION_MAX_LENGTH = 50
QUESTION_MIN_LENGTH = 10

OPTION_MAX_LENGTH = 20
OPTION_MIN_LENGTH = 1
OPTION_COUNT = 4

#Quiz Settings
QUIZ_COUNT_OF_QUESTIONS_LIST = [7, 10, 14]
QUIZ_COUNT_OF_QUESTIONS = QUIZ_COUNT_OF_QUESTIONS_LIST[0]
QUIZ_TIME_LIMIT_LIST = [10, 13, 16]
QUIZ_TIME_LIMIT = QUIZ_TIME_LIMIT_LIST[0]


# Main menu buttons
MAIN_MENU_START_QUIZ_BUTTON = "🎮 کوییز"
MAIN_MENU_LEADERBOARD_BUTTON = "📊 آمار من"
MAIN_MENU_GLOBAL_LEADERBOARD_BUTTON = "🏆 رتبه‌بندی"
MAIN_MENU_HELP_BUTTON = "🔍 راهنما"
MAIN_MENU_SUBMIT_QUESTION_BUTTON = "🎯 ارسال سوال جدید"
